server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accepted
    username: postgres
    password: root
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
    clear-checksums: true

